create memebers details screen
antonpashdev/iw_app pull request #23
Opened 2023-04-14 15:46 UTC by greengnome

2023-04-14 17:55 UTC, antonpashdev requested changes

2023-04-14 17:55 UTC, antonpashdev commented on lib/screens/organization/members_details_screen.dart
> +            child: Image.network(
надо быть последовательными) есть виджет NetworkImageAuth

2023-04-14 17:55 UTC, antonpashdev commented on lib/screens/organization/members_details_screen.dart
> +        Column(children: [avatar]),
зачем тут Column?

2023-04-14 17:55 UTC, antonpashdev commented on lib/screens/organization/members_details_screen.dart
> +                                if (snapshot.data == null) {
if (!snapshot.hasData) ..

2023-04-14 17:55 UTC, antonpashdev commented on lib/screens/organization/members_details_screen.dart
> +                  isLast ? Container() : const Divider()
if (!isLast) const Divider()

2023-04-14 17:55 UTC, antonpashdev commented on lib/screens/organization/members_details_screen.dart
> +              color: COLOR_GRAY, fontSize: 12, fontWeight: FontWeight.w300))
ставь запятые плииииз - это x100 к ридабилити
color: COLOR_GRAY, fontSize: 12, fontWeight: FontWeight.w300),),

2023-04-14 17:55 UTC, antonpashdev commented on lib/screens/organization/org_details_screen.dart
> +            AppPadding(
можно обернуть Row в AppPadding, а не каждый child

2023-04-15 17:30 UTC, greengnome commented on lib/screens/organization/members_details_screen.dart
> +            child: Image.network(
Done

2023-04-15 17:31 UTC, greengnome commented on lib/screens/organization/members_details_screen.dart
> +        Column(children: [avatar]),
Removed

2023-04-15 17:32 UTC, greengnome commented on lib/screens/organization/members_details_screen.dart
> +                                if (snapshot.data == null) {
Fixed

2023-04-15 17:33 UTC, greengnome commented on lib/screens/organization/members_details_screen.dart
> +                  isLast ? Container() : const Divider()
Done

2023-04-15 17:33 UTC, greengnome commented on lib/screens/organization/members_details_screen.dart
> +              color: COLOR_GRAY, fontSize: 12, fontWeight: FontWeight.w300))
ok

2023-04-15 17:35 UTC, greengnome commented on lib/screens/organization/org_details_screen.dart
> +            AppPadding(
Done

2023-04-15 18:20 UTC, antonpashdev approved these changes

2023-04-15 18:21 UTC, merged