create-user-flow
antonpashdev/iw_app pull request #5
Opened 2023-03-11 14:16 UTC by kirillgladkov

### Change log
- implement user nickname screen 
- implement user name screen
- create `BasicApi` and `UsersApi`
- create `AppStorage` class

### Added 3-rd parties
- added `dio` lib - http request helper
- added `flutter_secure_storage` lib - store JWT token etc.
- added file_picker - pick files from FS

2023-03-11 19:49 UTC, antonpashdev requested changes

2023-03-11 19:49 UTC, antonpashdev commented on lib/api/users_api.dart
> +  final _dioClient = Dio(BaseOptions(
зачем, если это есть у BaseApi?

2023-03-11 19:49 UTC, antonpashdev commented on lib/theme/app_theme.dart
в этом файле изменяется только индентация? если да, то настрой свой форматтер :)

2023-03-11 19:49 UTC, antonpashdev commented on lib/screens/create_user.dart
> +    final startsWithAt = trimmedValue!.startsWith(RegExp(r'^@'));
юзер пишет символ '@' ? у TextFormField есть параметр prefix

2023-03-13 20:24 UTC, antonpashdev commented on lib/screens/create_user.dart
> +class CreateUser extends StatefulWidget {
давай придерживаться одного стиля)
имена классов скринов заканчиваем на Screen, а имена файлов на _screen

2023-03-13 20:31 UTC, antonpashdev requested changes

2023-03-13 20:31 UTC, antonpashdev commented on lib/widgets/scaffold/screen_scaffold.dart
> +        leading: GestureDetector(
кнопка Назад добавляется автоматически, так шо оно тут не надо

2023-03-13 20:31 UTC, antonpashdev commented on lib/screens/create_user.dart
> +class CreateUser extends StatefulWidget {
давай придерживаться одного стиля)
имена классов скринов заканчиваем на Screen, а имена файлов на _screen

2023-03-14 19:12 UTC, kirillgladkov commented on lib/screens/create_user.dart
> +    final startsWithAt = trimmedValue!.startsWith(RegExp(r'^@'));
prefix только визуально подставляет значение но дата в колбеке приходит без префикса

2023-03-14 19:12 UTC, kirillgladkov commented on lib/theme/app_theme.dart
ок

2023-03-14 19:12 UTC, kirillgladkov commented on lib/api/users_api.dart
> +  final _dioClient = Dio(BaseOptions(
убрал

2023-03-14 19:13 UTC, kirillgladkov commented on lib/widgets/scaffold/screen_scaffold.dart
> +        leading: GestureDetector(
это для оформление

2023-03-14 19:45 UTC, antonpashdev commented on lib/theme/app_theme.dart
ну верни индентацию как было, ну будь человеком)

2023-03-14 19:49 UTC, antonpashdev approved these changes

2023-03-14 19:50 UTC, merged